import{a as L,S as v,i as n}from"./assets/vendor-C4-ZuMk8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function f(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=f(t);fetch(t.href,o)}})();async function g(r,e,f=1,l=15){try{return(await L.get("https://pixabay.com/api/",{params:{key:e,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:f,per_page:l}})).data}catch(t){throw console.error("Error fetching images:",t),new Error("Failed to fetch images")}}function m(r){return r.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
      <div class="info">
        <p> ${e.likes} </br> Likes</p>
        <p> ${e.views} </br> Views</p>
        <p> ${e.comments} </br> Comments</p>
        <p> ${e.downloads} </br> Downloads</p>
      </div>
    </a>
  `).join("")}const b="46893136-84096bff0dd45fd4b99afcbdb",h=document.querySelector("#search-form"),d=document.querySelector("#gallery"),y=document.querySelector("#loader"),s=document.querySelector("#load-more-btn");let w=new v(".gallery a"),c="",i=1;const a=15;let p=0;h.addEventListener("submit",async function(r){if(r.preventDefault(),c=h.querySelector("input").value.trim(),i=1,!c){n.warning({title:"Warning",message:"Please enter a search keyword."});return}d.innerHTML="",y.style.display="block",s.style.display="none";try{const e=await g(c,b,i,a);p=e.totalHits,e.hits.length===0?n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):(d.innerHTML=m(e.hits),w.refresh(),e.hits.length===a&&p>a&&(s.style.display="block"))}catch{n.error({title:"Error",message:"Something went wrong, please try again later."})}finally{y.style.display="none"}});s.addEventListener("click",async function(){i+=1,y.style.display="block",s.style.display="none";try{const r=await g(c,b,i,a);r.hits.length>0?(d.insertAdjacentHTML("beforeend",m(r.hits)),w.refresh(),r.hits.length<a||i*a>=p?(n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),s.style.display="none"):s.style.display="block",S()):(n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),s.style.display="none")}catch{n.error({title:"Error",message:"Something went wrong, please try again later."})}finally{y.style.display="none"}});function S(){const r=d.firstElementChild;if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
